codecov:
  require_ci_to_pass: false  # CI 성공 여부와 관계없이 PR 코멘트 추가

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false  # 변경 사항이 없어도 PR에 항상 코드 커버리지 코멘트 추가
  branches:
    - main
    - develop
