codecov:
  require_ci_to_pass: false  # CI 성공 여부와 관계없이 PR 코멘트 추가

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false  # 변경 사항이 없어도 PR에 항상 코드 커버리지 코멘트 추가
  after_n_builds: 1  # 최소 1개의 CI 빌드가 완료된 후 댓글 추가
  show_critical_paths: true  # 중요한 커버리지 경로 표시
  branches:
    - main
    - develop
    - - "*"
